### ISSUE TITLE
Change the code to not log PII in the future

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#1011] opened 2022-11-28 19:15 UTC
_Change the code to not log PII in the future_

## Description

As a (user), I need to be able to do (X) so that I can achieve (Y) outcome. 

WHY are we building?
WHAT are we building?
VALUE created by our solution

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Change our code so in future when we have a duplicate key error, we don't dump PII into our logs

- [ ] Generate appropriate log messages so that executions of this feature can be tracked
- [ ] Can misuse of this feature cause harm? If yes, create an alert

* Privacy considerations

## QA Steps

- [ ] Tested in a realistic production scenario

**Comment by sastels** [comment] 2022-12-13 19:39
I think this is a duplicate of #1025... looking at the Acceptance Criteria here, are there additional things we should be doing that aren't captured in #1025?

**Comment by yaelberger-commits** [comment] 2022-12-13 19:59
This is the same @sastels. I will move this one to Closed.

**Closed** 2022-12-13 19:59 UTC
