### ISSUE TITLE
Last allowed email not sent right away, delayed 4:15hours

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#1089] opened 2023-02-02 16:30 UTC
## Describe the bug 

Last allowed email of the day gets created but not sent. 

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3

## To Reproduce

1. Set your daily limit to 2
2. Send an email through the api. it gets sent.
3. Send another email through the api. You get a 201 back, the email is created in the database but not sent.

## Expected behavior

Email is sent

## Impact

If a service goes up to its daily limit, the last email will not send. After 4hrs 15 minutes the `replay_created_notifications()` task will send it automatically.

## Additional context

```
[2023-02-02 14:30:33,240: INFO/ForkPoolWorker-2] email 8181b70b-e118-4b65-bcf1-5e35313b86af created at None
[2023-02-02 14:30:33,253: INFO/ForkPoolWorker-2] Sending following email notifications to AWS: dict_keys(['8181b70b-e118-4b65-bcf1-5e35313b86af'])
[2023-02-02 14:30:33,540: INFO/ForkPoolWorker-2] Exceeded send limits (2) for today: Email 8181b70b-e118-4b65-bcf1-5e35313b86af not created
```

**Note that our anticipated work to move to an "email daily limit" analogous to the sms fragment limit should fix this.**

**Comment by yaelberger-commits** [comment] 2023-03-09 15:15
Should check if the same behaviour is reproduced in Admin, or just API
This would get fixed once we go to SMS limits v2 and daily email limits

**Comment by yaelberger-commits** [comment] 2023-03-30 14:36
We may have fixed this, @andrewleith will check to confirm in the coming weeks

**Comment by andrewleith** [comment] 2023-05-01 11:11
I think this is still an issue.  To revisit when we tackle #887

**Comment by yaelberger-commits** [comment] 2023-08-03 14:57
Timeboxed 2 days for investigation next sprint

**Comment by smcmurtry** [comment] 2023-08-29 16:03
I was not able to reproduce this bug in my tests. This bug is now fixed!

Here is what I did:

- set my daily email limit to 2 for one of my services on Prod (id: 1aaea8aa-974c-4d45-9476-0d93e0c53342)
- sent 1 email to myself via the one-off email endpoint: `/v2/notifications/email`, got a success response and recieved the email right away
- sent 1 more email to myself via the one-off endpoint, got a success response and recieved the email right away (no 4 hour delay was observed)
- tried to send 1 more one-off email, got the correct failure response: `{"status_code": 429, "errors": [{"error": "LiveServiceTooManyEmailRequestsError", "message": "Exceeded email daily sending limit of 2 messages"}]}`

Next test using the bulk endpoint
- set my daily email limit to 6
- sent a bulk send of 2 emails to myself, recieved both right away
- sent another bulk send of 2 emails to myself, again recieved both right away
- tried the bulk send again and got the correct failure response

Next test using the admin one-off sending flow
- increased daily limit by 2 to 8 emails/day
- sent 2 emails to myself via the one-off admin flow, recieved right away
- the next attempt to send fails as expected

Next test using the admin csv sending flow
- increased daily limit by 2 to 10 emails/day
- sent 2 emails via csv to myself, recieved right away
- the next attempt to send fails as expected

**Closed** 2023-08-31 17:13 UTC
Labels: Bug | Bogue, Medium Priority  | Priorité moyenne
