### ISSUE TITLE
Create a clearer path to finding guidance on the 'Edit template' screen

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#410] opened 2022-02-16 22:38 UTC
# Description

As a Sender, I need a clear path to finding the guidance so that I can focus on learning how to drafting my message. 

WHY are we building?
[It didn't seem clear to participants that there were 2 distinct guides for different information. For participants that happened to open the formatting guide first, it was easy for them to associate it to the formatting task. These participants expected to find information on how to add variables in the formatting guide before they saw that there's a second guide.](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwEUFgBd0KLqH7oo/recdF9bi1REiY6W5V?blocks=hide)

[There was friction finding and using guides. There seemed to be some unnecessary friction caused by the location of the guides ...
](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwQUX3tUxbMxYS7C/rec3YltlZdAYUvcUY?blocks=hide)
WHAT are we building?
Better path to finding guidance on the 'Edit template' screen

VALUE created by our solution
More seamless UX for Senders, especially if they're not familiar with Markdown.

# Acceptance Criteria** (Definition of done)

- [ ] Either it is made clearer that there are two guides, or all the guidance related to drafting/editing a template is found in one place.
- [ ] Designs updated in English and French
- [ ] Team review
- [ ] Design critiques (a11y)
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

Given a Sender who is drafting/editing a message, when they try to format or add variables to their template, then they're able to find the guidance with a quick scan.

**Comment by yaelberger-commits** [comment] 2022-02-17 19:39
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/410?planning-poker) with ZenHub @amazingphilippe @YedidaZalik @adriannelee

**Comment by yaelberger-commits** [comment] 2022-03-07 18:45
Wait until we have everyone on the design team here to work on it, pushing back to a future sprint

**Comment by amazingphilippe** [comment] 2022-07-11 13:24
Maybe a duplicate of #404

**Comment by yaelberger-commits** [comment] 2022-07-13 12:50
@amazingphilippe #404 was specifically about guidance for sending bulk using a spreadsheet. 
I think this one is broader than that, and speaks to users' difficulty finding guidance for formatting and personalizing messages at the actual moment they need that guidance, when they are creating and editing a template. 
Perhaps some of the changes to the guidance section has resolved some of this, but is there now a clear path from the "edit template" screen to the guidance documents?

**Comment by amazingphilippe** [comment] 2022-07-13 17:13
> is there now a clear path from the "edit template" screen to the guidance documents?

Yes you are right, this is probably what I was getting at. There is a better guidance index now, and the updates to the edit-template screen will address this. Given the issues # are pretty close, I think we probably just forgot to bring this one along as we designed the help card component.

**Comment by yaelberger-commits** [comment] 2022-07-13 17:25
I will close it then @amazingphilippe 
We need to update the research airtable to show where we've completed this work. Can you link to the Figma artifacts in airtable please?

**Closed** 2022-07-13 17:26 UTC
Labels: Medium Priority  | Priorité moyenne, UX, Refined
