### ISSUE TITLE
Unexpected focus switch.

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#483] opened 2022-03-16 14:46 UTC
# Templates, Status

Visibility: 3
Evaluation: Partially Supports
Success Criteria: 3.2.2: On Input
Needs design: 

### Description
Tab interfaces such as those on the Messages Sent and Templates pages, behave as links, triggering page reloads. This causes the tab navigation/focus to start at the top of the page after a tab has been selected, instead of focus remaining on the selected tab. Rather than a tablist, the tabs could be treated like navigation (similar to pagination links) as a list of links within a <nav> element with the current one marked using aria-current.

![](https://dl.airtable.com/.attachments/c67eaaad3379f7db6427455b86d5804e/7436d41d/Capturedecranle2022-03-15a13_45_10.png)

**Comment by amazingphilippe** [comment] 2022-03-23 14:00
Duplicate of #498

**Closed by amazingphilippe** 2022-03-23 14:00 UTC
Labels: Accessiblity | Accessibilité
