### ISSUE TITLE
reply-to doesn't work if uploading csv

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#462] opened 2022-03-14 17:48 UTC
## Describe the bug 

The reply-to-text field of the notification is not set correctly for csv uploads

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-2? most services aren't using a reply-to, but a fair number are.

More precisely, approximately 15% of our notifications are sent where a reply-to is set in the service, but not used when the notification is sent.

```
with n as (
    select id, created_at, reply_to_text, service_id from notifications
    where notification_type = 'email'
),
rt as (
select created_at as rt_created_at, email_address as rt_reply_to, service_id
from service_email_reply_to
where archived = false
),
data as (
select n.*, rt_created_at, rt_reply_to from n join rt on n.service_id = rt.service_id
where rt_created_at < created_at
),
bad as (
select distinct id, service_id from data
where reply_to_text = ''
)
select count(*) from bad

-- RESULT 115760

select count(*) from notifications

-- RESULT 793057
```

What services?

```
with n as (
    select id, created_at, reply_to_text, service_id from notifications
    where notification_type = 'email'
),
rt as (
select created_at as rt_created_at, email_address as rt_reply_to, service_id
from service_email_reply_to
where archived = false
),
data as (
select n.*, rt_created_at, rt_reply_to from n join rt on n.service_id = rt.service_id
where rt_created_at < created_at
),
bad as (
select distinct id, service_id from data
where reply_to_text = ''
)
select name, count(*) from bad join services on service_id = services.id
group by name
order by count desc
```
![image.png](https://images.zenhubusercontent.com/614cd50770420efff7535b31/bca21f17-6452-4a97-9de9-903bc8f995ae)

Looking at Feb 14 - March 14 data, 44 out of 93 live services that sent a notification had a reply-to set.
```
with live_services as (
    select * from services
    where active = true and restricted = false and count_as_live = true
),
recent_emails as (
    select * from notification_history
    where created_at > '2022-02-14' and created_at < '2022-03-14'
    and notification_type = 'email'
),
recent_live_emails as (
    select recent_emails.* 
    from recent_emails join live_services
    on recent_emails.service_id = live_services.id
),
rt as (
    select *
    from service_email_reply_to
    where archived = false
)

select count(distinct(recent_live_emails.service_id))
from rt join recent_live_emails on rt.service_id = recent_live_emails.service_id
-- 44

select count(distinct(service_id))
from recent_live_emails
-- 93
```

## To Reproduce

1. Go a service, then Settings. set a reply-to address (under Emails)
2. choose an email template
2. upload a csv and send to yourself
3. click "reply" in your email app. Note that the "to" address is the sending address of your service, not the "reply to" that you specified.

Note that sending one email to yourself (ie not using the csv upload) gives the email the correct reply-to.

## Expected behavior

- [x] reply-to set correctly
- [x] User who reported the issue in support ticket #9012 is notified when fix is in place

## Impact

Impact on Notify users:
- Services that want their users to be able to easily reply to them cannot use the csv upload.

Impact on Recipients:
- recipients who get these emails cannot click "reply" to reply.

## Additional context

help desk ticket https://cds-snc.freshdesk.com/a/tickets/9012

Note that the user who reported the issue asked to be is notified of an estimate for when we would fix the issue.

**Comment by yaelberger-commits** [comment] 2022-03-17 14:19
Preliminary work to know the impact of this bug: Query how many users use the reply-to field using bulk upload with CSV

**Comment by yaelberger-commits** [comment] 2022-03-24 17:18
High priority in Product Backlog because we want to prioritize finding out the impact of this bug. Query how many users use the reply-to field using bulk upload with CSV. Needs a bit more information about the problem and possible fix so anyone on the team can pick up the bug and fix.

**Comment by yaelberger-commits** [comment] 2022-03-28 19:07
Moved to Product Backlog to assess how many users are impacted by this bug so we can prioritize this bug

**Comment by yaelberger-commits** [comment] 2022-04-20 17:27
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/462?planning-poker) with ZenHub @iokpala

**Comment by yaelberger-commits** [comment] 2022-04-27 13:17
A few duplications at play, Ikenna working on this today

**Comment by yaelberger-commits** [comment] 2022-05-02 12:42
@iokpala can you add your updates to the card please from last week? Thanks!

**Comment by yaelberger-commits** [comment] 2022-05-02 13:06
Tests passing locally, but not passing in staging
Need to set up in preview

**Comment by iokpala** [comment] 2022-05-02 20:13
Was able to figure out the difference and why tests were passiing locally.. Made progress with resolving the failing tests from 76 to 23.. 

Spuning out of this is the need to restructure the test to be more modular and reduce ducplication.. this amongst my find.. to the wider project we need to a bit mptore concious of GIVEN WHEN THEN model of testing.

**Comment by iokpala** [comment] 2022-05-04 23:25
Preliminary QA found when a custom reply_to is set the following error occurs.. possibly due to sender_id being None.. 

Will attempt to reproduce this via a test and work to resolve it. 

``` 
File "/workspace/app/celery/tasks.py", line 132, in process_job
    process_rows(result, template, job, service)
  File "/workspace/app/celery/tasks.py", line 217, in process_rows
    "reply_to_text": dao_get_reply_to_by_id(service.id, sender_id).email_address,
  File "/workspace/app/dao/service_email_reply_to_dao.py", line 25, in dao_get_reply_to_by_id
    db.session.query(ServiceEmailReplyTo)
  File "/home/vscode/.local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 3500, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```

**Comment by jimleroyer** [comment] 2022-05-09 13:06
Currently needs a bit of polishing with the PR review.

**Comment by yaelberger-commits** [comment] 2022-05-16 13:18
Bug is fixed, cleaning up PR

**Comment by yaelberger-commits** [comment] 2022-05-25 12:37
@sastels Can we consider this card closed now? thanks!

**Closed** 2022-05-26 15:21 UTC
Labels: Bug | Bogue, High Priority | Haute priorité, Refined
