### ISSUE TITLE
Stuck email status: Missing reference on email notification status update

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#718] opened 2022-06-22 14:17 UTC
# Bug 

Some email notifications are stuck in the `sending` state, as these can't be found in the database by reference, despite the fact that these very well exist with proper that reference.

For example: `notification not found for reference: 70ea849e-1ad6-4329-a3e7-3d798b28669f (update to delivered)`. That reference though exist in the database. It might be similar to another bug we have sometimes when we save a notification in the database and we're about to send it, but the sending process is too quick for the database to replicate the data among readers.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)

SEV3

## To Reproduce

1. Send an email notification.
2. Pray to the database gods that data replication is slow enough and AWS callbacks super quick to have this issue surface.
3. Observe the notification stuck in the `sending` status. If that doesn't work, you didn't try hard enough at # 2. Rinse and repeat.

Collecting historic data to observe this is better than replicating, because it can't be triggered normally unless we'd induce some delay in the AWS components.

# Expected behavior

No notifications are stuck in the sending state due misread reference read.

* We can review / instill a retry task for callbacks from AWS. 
* We could put in some delays on callback received tasks to wait for the db data replication to occur.

# Impact

## Impact on Notify users:

This leads to confusion among users as they think Notify didn't sent the notifications. There is a lack of trust in the software.

## Impact on Recipients:

They might never receive an intended email if the sender was not notified that the recipient is in the suppression list. Being part of that list might be due to a complaint to an unrelated service also using Notify.

## Impact on Notify team: 

More support tickets on our end.

# Additional context

Discovered while working [on that investigation card](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/695).

**Comment by sastels** [comment] 2023-01-13 19:50
For example, we have notification
```
id	created_at	notification_status	reference
3c2d00c5-23ee-4306-be6f-04196a0d1893	2023-01-13 19:08:23.955267	sending	5ce018f6-6a8f-46ee-948a-e756b93cef5a
```
And in cloudwatch
```
2023-01-13 19:08:24,233: WARNING/ForkPoolWorker-2] notification not found for reference: 5ce018f6-6a8f-46ee-948a-e756b93cef5a (update to delivered)
```

**Comment by sastels** [comment] 2023-01-16 19:35
partly completed PR https://github.com/cds-snc/notification-api/pull/1731

**Comment by jimleroyer** [comment] 2023-01-16 21:16
Discussed with Steve and that task should be fairly quick and address some mislabeled failures.

**Comment by yaelberger-commits** [comment] 2023-01-18 14:09
PR to fix needs review

**Comment by whabanks** [comment] 2023-01-18 19:32
PR has been reviewed and approved. Some additional testing needed once it's in staging. [Details!](https://github.com/cds-snc/notification-api/pull/1731#pullrequestreview-1254181780)

**Comment by yaelberger-commits** [comment] 2023-01-23 14:10
PR still open. Will reviewed. Jumana took a look.

**Comment by yaelberger-commits** [comment] 2023-01-23 14:11
Ready to be merged

**Comment by andrewleith** [comment] 2023-01-25 14:10
- @jimleroyer will QA
- @sastels to add query to help qa this, since it doesn't happen often

**Comment by sastels** [comment] 2023-01-27 14:41
ok, something else is going on. Getting occasional logs like
```
notification not found for SNS reference: 5a5483cf-96ad-4be0-bd3f-c2b1679902a5 (update to delivered). Giving up.
```
Which means that we tried 5 times over half an hour and couldn't find a notification with this reference. Looking at the database - there is no notification with this reference! So basically we sent a text but did not record the reference.

This is a bigger problem than first thought. We should add logging around where we send.

Note that in the past week this has happened 62 times (that we've given up on finding a notification). Just for SNS, no failures for SES.

**Comment by andrewleith** [comment] 2023-01-30 14:09
- Adding retries fixed most of these issues
- For the remaining ones, there is no trace of these notifications - unclear what the problem is here

**Comment by jimleroyer** [comment] 2023-02-01 16:07
This issue might be a soft blocker on how we count bounce rate, it might bring inaccuracies if we can't properly map incoming email receipts from AWS back to the related notifications.
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/844

**Comment by jzbahrai** [comment] 2023-05-31 19:43
We fixed this as part of the PR that Steve implemented and the overall bounce rate feature. Along with the retries we have the statuses update. Statuses have also been updated to be consistent across the board.

**Closed** 2023-06-08 19:49 UTC
Labels: Bug | Bogue, Medium Priority  | Priorité moyenne, Dev
