### ISSUE TITLE
EXPLORE: Support any language (Esp Indigenous, other common non-EN/FR languages)

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#714] opened 2022-06-21 13:27 UTC
- **Support ticket:** https://cds-snc.freshdesk.com/a/tickets/9789

Arabic text requires right alignment 

[Product Requirements Document ](https://docs.google.com/document/d/11Vb7d3xtsnF8KB7cNzANaIbFPwHBOV0mtBM9ur-ZYUk/edit#heading=h.7v7874gk3y32)

## Related research
- (How it might be perceived by recipient) [The official English version is often consulted (official guides, website) because it seems more trustworthy even if the participant is francophone](https://airtable.com/appWwAmHwDLtpIyko/tbl38n7ofWYBuezFc/viwBYyaQxOttZ0IAw/recaaSbkEXH6uhCb6?blocks=hide)

**Comment by jimleroyer** [comment] 2022-12-01 20:05
Nice github conversation on support of RTL in Markdown:
https://github.com/community/community/discussions/8115

**Comment by YedidaZalik** [comment] 2023-02-09 18:59
Recently came across this article that might be helpful: https://uxdesign.cc/designing-a-robust-right-to-left-ui-in-arabic-hebrew-and-farsi-d1e662a09cfa

**Comment by adriannelee** [comment] 2023-12-20 14:07
Yael starting this work over the holidays - knowns, unknowns to document. Includes languages justified right. Andrew is helping on this too.

**Comment by foudamo** [comment] 2023-12-20 14:19
Adding previous documentation 
Here is some context for the support ticket on Arabic support:

1. - [Freshdesk ticket asking about arabic](https://cds-snc.freshdesk.com/a/tickets/9789)
 - [This never actually got resolved.  Things looked good on our end but the client did not reply in the end
2. - [Freshdesk ticket indicating other languages work, including Arabic](https://cds-snc.freshdesk.com/a/tickets/8173)
3. - [Freshdesk ticket indicating Arabic does not work
](https://cds-snc.freshdesk.com/a/tickets/14760)


**There are three problems with ticket #1** 
- Firstly, Arabic letters in a word need to be connected (like cursive in English). They are disconnected in the second image
- Secondly, Arabic sentences go the opposite direction of latin (right to left). The words in a sentence seem to change order. Their text seem to switch to the latin way of writing (left to right)
- Thirdly, Arabic text needs to be aligned to the right (unlike latin languages, which are aligned to the left). The alignement is wrong in both the original image and the second image
- Fourth, here's an example of how it should look when all three are fixed <img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTk0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9585116105a153db9efaea1fd6db9af3007fc77a/image.png" alt="image.png" />

**There are two problems with tickets #2** 
- It seems that writing a template formats the Arabic Unicode correctly (minus the text alignment). See screenshot below

**There are two problems with tickets #3** 
- The text seems to go through the changes I outlined above after its sent out?. See screenshot below 

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkY0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b41c8a1d67d0f90da6123dfa318c284b59dc66b/image.png" alt="image.png" />

**Comment by foudamo** [comment] 2023-12-20 14:21
Adding: I have just sent myself a test email, and the text displayed correctly (again, minus the text alignment, which I think might be an easy fix). Please see screenshot below

<img width="1257" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMko0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--40db71b3d1fce74bd2d22a36744828c7605dbca1/image.png" alt="image.png" />

**Comment by yaelberger-commits** [comment] 2023-12-28 14:38
PRD has been started to organize user needs and business needs, set goals and non-goals and begin planning the features needed. Next step would be a team review at Story Refinement when everyone's back

**Comment by yaelberger-commits** [comment] 2024-09-03 17:24
Closed because duplicate of #1551

**Closed** 2024-09-03 17:23 UTC
Labels: Dev
