### ISSUE TITLE
Admin service dashboard not showing past notifications when using Lambda API

### ISSUE THREAD

**Issue by patheard** [cds-snc/notification-planning#635] opened 2022-04-26 12:38 UTC
## Describe the bug 

When the admin service's `API_HOST_NAME` is set to the Lambda API, a service dashboard does not show past notifications:

![image.png](https://images.zenhubusercontent.com/6141f63cba17b3613a6dcef0/8cf7aba8-a72b-4b15-aea2-1122c311ddc3)

The post notifications are only shown when the admin service `API_HOST_NAME` is set to use the Kubernetes API pod.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
SEV-2

## To Reproduce

1. Set admin service `API_HOST_NAME` to Lambda API URL.
2. Login to Admin.
3. View a service's notifications.  No messages will be found.

```sh
https://$BASE_DOMAIN/services/$SERVICE_ID/notifications
```

## Expected behavior

The service's past notifications are shown in a list.

### Impact on Notify users:
Users will not be able to view and search for the past notifications sent by their service.

**Comment by patheard** [comment] 2022-04-26 19:05
Current theory is that the API Gateway + Lambda proxy is not supporting multi-value parameters, which are used in this request to pass the `status`.

This works against Kubernetes:
https://api-k8s.staging.notification.cdssandbox.xyz/service/27949b45-795f-4570-a1fd-a401fd19717b/notifications?template_type=email&limit_days=7&status=delivered&status=failed&status=delivered&status=foo

This same request does not work against the Lambda - only the last `status=foo` is considered and no results are returned:
https://api-lambda.staging.notification.cdssandbox.xyz/service/27949b45-795f-4570-a1fd-a401fd19717b/notifications?template_type=email&limit_days=7&status=delivered&status=failed&status=delivered&status=foo


The following utility script was written to make local testing of the API easier:
```python
import calendar
import os
import time

import jwt

def create_jwt_token(secret, client_id):
    __algorithm__ = "HS256"
    __type__ = "JWT"

    headers = {
        "typ": __type__,
        "alg": __algorithm__
    }

    claims = {
        'iss': client_id,
        'iat': epoch_seconds()
    }
    t = jwt.encode(payload=claims, key=secret, headers=headers)
    if isinstance(t, str):
        return t
    else:
        return t.decode()
    
def epoch_seconds():
    return calendar.timegm(time.gmtime())

if __name__ == '__main__':
    token = create_jwt_token(os.getenv("ADMIN_CLIENT_SECRET"), os.getenv("ADMIN_CLIENT_USER"))
    print(token)
```

**Comment by patheard** [comment] 2022-04-26 20:14
And confirmed that it was multi-value parameter parsing causing the problems.  Fix was to switch the Lambda proxy event handler to the [apig-wsgi](https://github.com/adamchainz/apig-wsgi) module, which provides support for it.

**Comment by yaelberger-commits** [comment] 2022-04-27 13:08
Needs someone to go through staging and do a regression test

**Comment by jimleroyer** [comment] 2022-04-27 14:16
Tested the bulk upload path in the staging UI with @patheard , as we were talking about life and 42 in a random call.

**Comment by sastels** [comment] 2022-04-27 14:56
So are we good to switch the API_HOST_NAME in staging to point to the lambda? Perhaps let that simmer for a week or so before prod switch to see if we notice any other oddities?

**Comment by patheard** [comment] 2022-04-27 15:05
So Staging already has its `API_HOST_NAME` pointing at the Lambda.  Prod is still pointing at the k8s API pod (manual change was made the deployment).

The next Prod release we do will update Prod to point to the Lambda as well, but I could roll that back in the manifest repo if we want it to sit more.

**Comment by patheard** [comment] 2022-05-03 21:39
Staging has been updated to use the Lambda API for all services.  As a result, this can be tested, and once we're happy with the change, the same fix can be applied to the Production `API_HOST_NAME`.

**Comment by sastels** [comment] 2022-05-05 15:38
Verified that the problem is fixed on staging. We should proceed with the prod change.

**Closed** 2022-05-09 19:57 UTC
Labels: Bug | Bogue, Medium Priority  | Priorité moyenne
