### ISSUE TITLE
Service names in "from" field have accents removed

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#952] opened 2022-10-24 15:39 UTC
## Describe the bug 

We convert the service name to ascii when we put it in the "from field". This removes all accents.

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-3 Minor
Does not affect functionality, but it could make end users question how well the government supports bilingualism

## To Reproduce

1. Put an accent in your service name
2. Send yourself an email
3. See that the service name in the "from" 

## Expected behavior

From line has the accent in the service name

## Impact

End users see that services are missing accents and are annoyed.

## Additional context

AWS doesn't fully support unicode in email addresses, however it looks like it would be allowed in the service name.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ses.html#SES.Client.send_raw_email

Discovered via a support ticket: https://cds-snc.freshdesk.com/a/tickets/9718

## QA
- [ ] verify that accents in the service name are in the From field
- [ ] notify the user who sent the support ticket that the issue has been fixed

**Comment by yaelberger-commits** [comment] 2022-10-26 17:29
Close because this card is a duplicate of #898

**Closed by yaelberger-commits** 2022-10-26 17:29 UTC
Labels: Bug | Bogue, Bilingual | Bilingue, Support l Soutien
