### ISSUE TITLE
Create a healthcheck for the notify admin homepage

### ISSUE THREAD

**Issue by andrewleith** [cds-snc/notification-planning#757] opened 2022-07-06 18:21 UTC
Create a healthcheck for the homepage so we can be notified if it is ever down.

Tasks:
- [ ] Create a route 53 healthcheck in AWS
- [ ] Create a cloudwatch alarm to let us know if the healthcheck fails

**Comment by yaelberger-commits** [comment] 2022-08-11 14:04
Closed because it's a duplicate of #754

**Closed by yaelberger-commits** 2022-08-11 14:04 UTC
