### ISSUE TITLE
Need a Notify FR homepage in GC Articles

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#460] opened 2022-03-11 13:37 UTC
_Need a Notify FR homepage in GC Articles_

## Description

There’s currently no way for the Notify site using GC Articles to share a link to the french homepage.

WHY are we building?
We need a FR homepage for Notify that we're rebuilding in GC Articles
WHAT are we building?

The solve to for a FR home page is on the Notify routing side ---
GC Articles + the Wildcard route falls at the end of the line --- basically if a route doesn't exist in Notify -> GC Articles tries to find a matching page and serve that up.
If your looking for a FR link for the HomePage I would propose adding a /fr route within Notify and serve up GC Articles content from that page.  The Français link on the HomePage could link to /fr.
That should solve for the HomePage.

This is an issue that needs to be addressed within the Notify codebase itself, as the homepage is a special case (it always has a / permalink in both languages).

Tim’s suggestion is to add a route to “/fr” that is hard-coded to return the french homepage content, which is probably the easiest way to solve this.

VALUE created by our solution
We can serve visitors to the site in English or French

## Acceptance Criteria** (Definition of done) 

_To be refined through discussion with the team_

Given some context, when (X) action occurs, then (Y) outcome is achieved 

If this user story emerged from User Research insights:
- [ ] Link research insight back to hypothesis from Epic or Objective in Airtable
- [ ] Once change/fix/feature is implemented, mark insight as "resolved" in Airtable
- [ ] Once change/fix/feature is implements, link insight to design artifacts (Figma) in Airtable

* A11y
* Bilingualism
* Privacy considerations
* Security controls in place
* Measuring success and metrics

**Comment by jimleroyer** [comment] 2022-03-11 14:59
Just want to confirm that this is indeed on the Notify side. We retrieve sections of text from GCArticles from Notify page: the latter still controls which page to display based on a requested URL. Notify do send to GCArticles a language to retrieve and display, but it's all on GCNotify side still.

This card might be a duplicate of:
https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/284

I don't think GCArticles need additional work, what they have should do it. Tim's suggestion to have `/fr/` in the link rather than using a parameter might be best for bookmarking and sharing links in general.

**Comment by amazingphilippe** [comment] 2022-04-21 16:02
Linking to a specific language on the root directory:
https://github.com/cds-snc/notification-admin/pull/1240

**Comment by yaelberger-commits** [comment] 2022-05-18 13:15
@amazingphilippe is this also done now?

**Comment by amazingphilippe** [comment] 2022-05-24 18:43
There is now a way to link to the French home page: https://staging.notification.cdssandbox.xyz/accueil

Same with English: https://staging.notification.cdssandbox.xyz/home

We can still access https://staging.notification.cdssandbox.xyz/ (nothing after the domain) And this could be in French or in English, depending on the user's cookies.

**Comment by andrewleith** [comment] 2022-05-25 11:23
Yes this is my understanding as well.  Right now, as you said, the app will be in whatever language they selected if they visit `/`. I don't see a particular need to redirect to `/home` or `/accueil` when the user visits `/`, but it would be easy enough to do if there is a need.

**Comment by amazingphilippe** [comment] 2022-06-07 13:53
I think this issue is done. This issue was originally about setting a slug to the homepage in GC article, so that it could be accessed with the correct url. We don't need the redirect. I think we can close this now!

The fix is different from the solution in the story above, but the outcome is the same.

**Comment by yaelberger-commits** [comment] 2022-06-07 14:39
I will move to done, thanks for flagging @amazingphilippe and @andrewleith

**Comment by yaelberger-commits** [comment] 2022-06-14 17:16
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/460?planning-poker) with ZenHub @amazingphilippe

**Closed** 2022-06-20 12:55 UTC
Labels: Medium Priority  | Priorité moyenne, Bilingual | Bilingue, Public website l Site web public
