### ISSUE TITLE
Stuck email status: No update of status on received complaint

### ISSUE THREAD

**Issue by jimleroyer** [cds-snc/notification-planning#716] opened 2022-06-22 14:00 UTC
# Bug

Notifications that are in the suppression list [will not get their status updated but stuck at sending](https://github.com/cds-snc/notification-api/blob/bebd806cad9581101e5cc1d52db2613c1baa1fa9/app/celery/process_ses_receipts_tasks.py#L37). So it's neither still sending nor really delivered...

```
"complaintSubType\": \"OnAccountSuppressionList\", \"feedbackId\": \"010d018153144072-7cd19a78-5d64-4bf0-be89-bff19022d8b4-000000\
```

We might need to update the code that receives the response callback to update the status. It seems that there is logic that exist to take a complaint in (i.e. due to suppression list in this case) and [concert it as delivered](https://github.com/cds-snc/notification-api/blob/bebd806cad9581101e5cc1d52db2613c1baa1fa9/app/notifications/notifications_ses_callback.py#L66-L70), but this is not getting called. So practically, it seems Notify initially considers these as delivered... We might want to re-evaluate this, to make sure that that a complaint was tagged on it for sure.

# [Bug Severity]

SEV-3

# To Reproduce

1. Send email notification that is in the AWS suppression list
2. Observe the notification stuck in the `sending` status.

## Expected behavior

The notification should indicate that it was processed (delivered or failure) but not sent due to a complaint. The [current mapping logic](https://github.com/cds-snc/notification-api/blob/bebd806cad9581101e5cc1d52db2613c1baa1fa9/app/notifications/notifications_ses_callback.py#L66-L70) would have us mark this as `delivered`, which might be confusing. We need to test if it flags the complaint at least. If not, we should consider reworking the mapping and message to the UI (failure with a complaint?).

# Impact

## Impact on Notify users:

This leads to confusion among users as they think Notify didn't sent the notifications. There is a lack of trust in the software.

## Impact on Recipients:

They might never receive an intended email if the sender was not notified that the recipient is in the suppression list. Being part of that list might be due to a complaint to an unrelated service also using Notify.

## Impact on Notify team: 

More support tickets on our end.

# Additional context

Discovered while working [on that investigation card](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/695).

**Comment by yaelberger-commits** [comment] 2022-12-22 18:28
A job switches from Sending to Sent after a day or two, but we should try to address the root cause

**Comment by jzbahrai** [comment] 2023-01-12 18:14
I made a PR for this - but I need a little more information from Jimmy. Will follow up on this when hes back

**Comment by jzbahrai** [comment] 2023-01-20 15:33
1. Test if its the first time vs multiple times the email is on the supression list
2. process_ses_receipts_tasks 
3. ses_to_sqs_email_callbacks

**Comment by andrewleith** [comment] 2023-02-21 17:07
Just wanted to add some research that is relevant to this ticket. There are 2 cases here for complaints:
1) a true complaint, which is initiated by a user by clicking in the email client to say that a message is spam -> this email was definitely delivered, otherwise they could not do this
2) a complaint with subtype `OnAccountSuppressionList` -> this was definitely not delivered and should be marked as a permanent failure

According to [the AWS docs](https://docs.aws.amazon.com/ses/latest/dg/notification-contents.html#complaint-object) there is only one complaint subtype possible:
> The value of the complaintSubType field can either be null or OnAccountSuppressionList. If the value is OnAccountSuppressionList, Amazon SES accepted the message, but didn't attempt to send it because it was on the [account-level suppression list](https://docs.aws.amazon.com/ses/latest/dg/sending-email-suppression-list.html).

One thing that is confusing to me is that we can receive both "complaints" AND "bounces" (hard) that indicate an account is on the suppression list, I'll see if I can find out what scenarios lead to one or the other.

**Comment by jimleroyer** [comment] 2023-02-21 20:10
A bit more information, as discussion with @andrewleith brought back the root issue of this bug. We don't update the status in the database once we receive the complaint. Look at code over there:
https://github.dev/cds-snc/notification-api/blob/c98d4100280e9bff8282661a64c782222049e16b/app/celery/process_ses_receipts_tasks.py#L36-L38

So we cannot report these to our users or internally. We want to add a database status change as done there:
https://github.dev/cds-snc/notification-api/blob/c98d4100280e9bff8282661a64c782222049e16b/app/celery/process_ses_receipts_tasks.py#L60-64

**Comment by andrewleith** [comment] 2023-03-03 13:24
> So we cannot report these to our users or internally. We want to add a database status change as done there: https://github.dev/cds-snc/notification-api/blob/c98d4100280e9bff8282661a64c782222049e16b/app/celery/process_ses_receipts_tasks.py#L60-64

After looking into this a little further, it seems we do update the database on a complaint, just not the notifications table:
https://github.com/cds-snc/notification-api/blob/main/app/notifications/notifications_ses_callback.py#L89

I think this makes sense in that when we receive a complaint we don't overwrite the original status of the notification. What do you think @jimleroyer?

**Comment by jimleroyer** [comment] 2023-03-03 18:35
@andrewleith We might want to overwrite that notification status. Ideally, we could have a status history with a dedicated table so we could keep track of the responses and not overwrite, as you pointed out.

The issue we have at current time though is that a notification can get stuck in the `sending` state if it never received receipt other than the complaint, and it happens a lot. Just from today in the past hour, these notifications got complaints but never the SES receipt. And there are more, it's just a sample.

* https://notification.canada.ca/services/e9b8d628-021b-4e8a-ad3b-88a1bf7611cf/notification/33f639cf-f453-4d30-9714-e02f380d8fca
* https://notification.canada.ca/services/e9b8d628-021b-4e8a-ad3b-88a1bf7611cf/notification/351b2bbe-e1f7-41ba-8afc-746f7ea78dc3
* https://notification.canada.ca/services/e9b8d628-021b-4e8a-ad3b-88a1bf7611cf/notification/29f280f4-3f8f-4182-8815-bcf3e3b1c4a7
* https://notification.canada.ca/services/e9b8d628-021b-4e8a-ad3b-88a1bf7611cf/notification/36cd56da-72db-4a0d-8db0-d5647c65612b
* https://notification.canada.ca/services/e9b8d628-021b-4e8a-ad3b-88a1bf7611cf/notification/727b5298-afd5-448e-b8bc-e29f1597d9fe
* https://notification.canada.ca/services/e9b8d628-021b-4e8a-ad3b-88a1bf7611cf/notification/441a77d6-a530-4fc2-8f77-b8980f5b5fb0

Some others are marked as delivered but with no update on the actual complaint. It would be great to fix this too so these notifications are correctly labeled as complained about.

* https://notification.canada.ca/services/e31c03b2-450d-45f6-8a5d-ec2f3036154e/notification/0078b868-dae4-4b9b-ab2a-e3a73b006ee4
* https://notification.canada.ca/services/e31c03b2-450d-45f6-8a5d-ec2f3036154e/notification/77d05caf-2bae-4e36-867d-2e492ca54ccd

**Comment by andrewleith** [comment] 2023-03-07 13:48
Oh I understand the bug now.  So when we receive a complaint **of type** `OnAccountSuppressionList` we should update that notification to `permanent-failure` with a provider_response of `The email address is on the GC Notify suppression list`. 

I just tried sending to an address on the suppression list and everything worked correctly which is a little frustrating.  My notification was marked as `permanent-failure` and the `provider_response` was correctly set to "The email address is on the GC Notify suppression list". It seems as though this behaviour is not consistent from SES.  

In any event, [the SES docs do state](https://docs.aws.amazon.com/ses/latest/dg/notification-contents.html#complaint-object) that if you try to to send to an address on the account level suppression list you will get a complaint notification with a subtype of `OnAccountSuppressionList`.

**Comment by andrewleith** [comment] 2023-03-08 20:11
Ready for QA

**Comment by jzbahrai** [comment] 2023-03-27 12:59
looks good to me. can we merge to staging?

**Comment by andrewleith** [comment] 2023-03-27 13:45
Yes, will do this morning!

**Closed** 2023-04-13 14:54 UTC
Labels: Bug | Bogue, Medium Priority  | Priorité moyenne, Dev
