### ISSUE TITLE
Find root cause for out of memory error with and fix

### ISSUE THREAD

**Issue by yaelberger-commits** [cds-snc/notification-planning#378] opened 2022-02-10 21:06 UTC
# How to replicate

* Hit the Notify API until its pod crashes with an out of memory exception.

# Steps

- Replicate the out of memory error with and without the batch saving feature flags
Look up for the FF_REDIS_BATCH_SAVING env variable, defined in code over here: https://github.com/cds-snc/notification-api/blob/c843d7903a2d9f29af5a6d545496f6d2d9146526/app/config.py#L443
- Analyze logs and metrics to find root cause.

# Root cause

Once the Redis cache which tracks the daily rate limit per service will expire, Notify API will hit back the database to store it again in its cache. The issue is that the query is not optimized for its existing indexed columns.

# Required changes and acceptance criteria

- [x] The root cause is identified.
- [x] Increase the Redis cache expiration for daily service rate limit from 1h to 2h.
- [x] Optimize the SQL query fetching notification count per service to leverage the indexed columns.
- [x] Compare old and new query plan of the SQL query to make sure the indexes are properly used and the query cost is lower.

**Comment by patheard** [comment] 2022-02-11 15:51
Unit testing results and debugging happening on Slack in the following thread:
https://gcdigital.slack.com/archives/CV38DBNVA/p1644507559676549.

All test results were from tests running for over 1 hour with a load of 3,000 users, 20 users/second being run concurrently by Mohamed and myself (so total load was 6,000 users, 40 users/second).

# Results:
- Triggered `OOMKilled` api pod termination with `notify-api:b7a8ae8` Docker image (current Production version), batch saving disabled.  This shows that the [#incident-notify-socket-error](https://gcdigital.slack.com/archives/C0313JMDDUM) from last week was likely unrelated to the batch saving release.
- @jimleroyer identified that the Redis cache storing daily service limits expires after 1 hour, and causes an expensive database query to run, which spikes the pod memory use and they are restarted with `OOMKilled` termination reason.
- Also Triggered api pod termination with `notify-api:latest` Docker image (batch saving features), batch saving enabled.  Same underlying cause of Redis cache expiring and forcing an expensive query.

**Comment by jimleroyer** [comment] 2022-02-11 20:13
The PR I opened introduced these changes:

* The database query to get the notification count per service should now leverage proper columns index, executing it faster and removing a bottleneck on the database (and transitively all incoming requests through the API waiting for it).
* Temporarily reduces the Redis cache for storing the daily rate limit per service from 1 hour to 15 minutes in order to stress this error even more, assuming the database indexes are properly leveraged now. I will later change it back to 2 hours if everything goes as planned.

**Comment by patheard** [comment] 2022-02-14 21:10
Just completed performance testing with @jimleroyer PR merged:
https://gcdigital.slack.com/archives/CV38DBNVA/p1644867483934939

### Test
@mohamed-cds  and I both running 3,000 users, 20 users/second

### Results
* After 15 minutes with the Redis cache expired there was a resource usage and response time spike as the service count query was run against the database.  However, this was handled gracefully with no pods restarting and service returning to normal once the cache was refreshed.
* We continued running the performance test for another 60 minutes and did not see any further resource spikes or response time degradations.

All told, I'd say the root cause has been fixed :tada:

**Closed** 2022-03-07 16:05 UTC
Labels: High Priority | Haute priorité, Performance Test, Support
