### ISSUE TITLE
(Week 2) Calculating estimations based on the services that PTMs provide

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/notification-planning#981] opened 2022-11-02 17:06 UTC
### Questions to answer
* What's the estimate of volume for PTMs if we were to open up?

**Comment by jimleroyer** [comment] 2022-11-09 19:32
Potential duplicate of #980
What do you think @smcmurtry ?

**Comment by yaelberger-commits** [comment] 2022-11-15 14:29
Closing this card!

**Closed** 2022-11-15 14:30 UTC
